CLASS ztest_mca_enterprise DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTEST_MCA_ENTERPRISE IMPLEMENTATION.
ENDCLASS.
