CLASS ztest_lto_enterprise DEFINITION  PUBLIC FINAL CREATE PUBLIC FOR TESTING.
  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZTEST_LTO_ENTERPRISE IMPLEMENTATION.
ENDCLASS.
